server:
  port: 8002
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: saa-02-ollama


  ai:
    dashscope:
      api-key: ${ai-api-key}
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5:1.5b
