server:
  port: 8001

  servlet:

    ##大模型对话中文乱码UTF8处理
    encoding:
      force: true
      charset: UTF-8
      enabled: true

spring:
  application:
    name: SAA-01-HELLOWORD
  ai:
    dashscope:
      api-key: ${ai-api-key}
      chat:
        options:
          model: deepseek-v4-pro






