server:
  port: 10000
  tomcat:
    max-http-form-post-size: 104857600  # 100MB
    connection-timeout: 120000  # 2分钟

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
